jdbc.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
jdbc.url=jdbc:sqlserver://localhost\\SQLEXPRESS01;databaseName=QuanLyPhim;encrypt=true;trustServerCertificate=true
jdbc.username=sa
jdbc.password=12345