spring.application.name=duanweb
server.port=8080

# ==== SQL Server (giu nguyen cau hinh cu trong db.properties) ====
spring.datasource.url=jdbc:postgresql://db.moazxrfqelrmootqzauk.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Nhom1_Duanweb
spring.datasource.driver-class-name=org.postgresql.Driver

# ==== Upload file (poster phim) ====
# Thu muc thuc te tren dia de luu file upload (ngoai classpath, khong bi mat khi build lai)
app.upload-dir=uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
